name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install

      - name: Test
        run: npm run test:unit

      - name: Build
        env:
          APP_VERSION: ${{ secrets.VERSION }}
        run: VUE_APP_VERSION=$APP_VERSION npm run build

      - name: Copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          rm: true
          strip_components: 1
          source: dist
          target: /www/deploy-cache

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            export SHA=${GITHUB_SHA:0:8}
            cd /www
            cp -a deploy-cache/ releases/$SHA
            rm -f current
            ln -s releases/$SHA current
            cd releases && ls -t | tail -n +11 | xargs rm -rf
            echo "🍺 Done $SHA $COMMIT_ID"
            echo "🧨 should reload webserver"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
